# Generated by Django 4.2 on 2026-05-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='الترتيب')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('theory_content', models.TextField(verbose_name='الشرح النظري')),
                ('vulnerable_code', models.TextField(blank=True, verbose_name='كود الثغرة')),
                ('secure_code', models.TextField(blank=True, verbose_name='الكود الآمن')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('image', models.ImageField(upload_to='lesson/%Y/%m/', verbose_name='الصورة')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['order'],
            },
        ),
    ]
